title: DPP 2022 Documentation 
description: These are the cumulative project documentations of the course.
theme: just-the-docs

url: https://pretoms.github.io/dpp2022 

color_scheme: nil
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  Repository: https://github.com/pretoms/dpp2022
